import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import '@/styles/globals.css';
import {ThemeProvider} from '@/providers/theme-provider'
import { TooltipProvider } from "@/components/ui/tooltip";
import ConvexClientProvider from '@/providers/convex-client-provider';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
       
           <ConvexClientProvider>
        <ThemeProvider
        attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
<TooltipProvider>
  <main >{children}</main>
</TooltipProvider>
<Toaster richColors/>
        </ThemeProvider>
        </ConvexClientProvider>
        
       
      </body>
    </html>
  );
}
